---
app:
  name: Z-Dax
  domain: zsmartex.tech
  subdomain: test
render_protect: false
ssl:
  enabled: true
images:
  barong: zsmartex/barong
  peatio: zsmartex/peatio
  rango: zsmartex/rango
  coverapp: zsmartex/coverapp
  castle: zsmartex/castle
storage:
  provider: AWS
  bucketName: zsmartex
  accessKey: changeme
  secretKey: changeme
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.yUjD7teE9xaUHty2IR8OGX7u
  peatio_rails_token: s.f6qGfmXjwvSNi5dR49sF9KYV
  peatio_crypto_token: s.PW4b8l60bD3DJFWMcbCJwYFf
  peatio_upstream_token: s.QABqySqMEUGc7QfxMsl71CMx
  peatio_matching_token: s.1gKn89hCNKkzzsQU56hZDj3a
  barong_token: s.l8nI4mWi50iIN0bXHyuT79MM
  finex_engine_token: s.MzQ9noXNBI1x3vzTRyCUTmcP
database:
  host: db
  port: 5432
  user: root
  password: djtdjtdjtdjt
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.zoho.com
  port: 587
  user: business@zsmart.tech
  password: zEH1WA4gZf9Y
  sender_email: business@zsmart.tech
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  blockchain: true
  deposit: true
  deposit_coin_address: true
  withdraw_coin: true
  upstream: false
  peatio_cron_job: true
  finex_cron_job: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: true
  ieo_order_processor: true
  ieo_order_executor: true
